<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://malazemi.netlify.app/</loc>
    <lastmod>2025-04-27</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>https://malazemi.netlify.app/iadadia.html</loc>
    <lastmod>2025-04-27</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://malazemi.netlify.app/kutub.html</loc>
    <lastmod>2025-04-27</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://malazemi.netlify.app/malazem.html</loc>
    <lastmod>2025-04-27</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://malazemi.netlify.app/thania.html</loc>
    <lastmod>2025-04-27</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
</urlset>
